config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # disable sign up
  # https://stackoverflow.com/questions/39773890/how-to-remove-disable-sign-up-from-devise

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users', to: 'devise/registrations#update', as: 'user_registration'
  end
  resources :settings, only: [:edit, :update]
  root 'static_pages#home'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :user
	has_many_attached :images
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :user
	has_one_attached :image

	validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
									 message: "must be valid image format" },
					 size: { less_than: 5.megabytes,
					 		 message: "should be less than 5MB" }
	HEX_REGEX = /\A[#]{1}[a-fA-F0-9]{6}\z/
	validates :font_color, format: { with: HEX_REGEX }
	validates :body_color, format: { with: HEX_REGEX }
	validates :user_id, presence: true
end

app/models/setting.rb
class Setting < ApplicationRecord
	HEX_REGEX = /\A[#]{1}[a-fA-F0-9]{6}\z/
    validates :color, format: { with: HEX_REGEX, 
    							message: "must be in hex format" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :articles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
	before_action :store_user_location!, if: :storable_location?


	private

		def storable_location?
			request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
		end

		def store_user_location!
			store_location_for(:user, request.fullpath)
		end

		def after_sign_in_path_for(resource_or_scope)
			stored_location_for(resource_or_scope) || super
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:show]
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)
		@post.image.attach(params[:post][:image])
		if @post.save
			flash[:success] = "post created!"
			redirect_to root_url
		else
			render 'static_pages/home'
			@feed_items = Post.all
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
		if @post.save
			flash[:success] = "post updated"
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post = current_user.posts.find_by(id: params[:id])
		@post.destroy
		flash[:success] = "Post destroyed :)"
		redirect_to root_url
	end

	private

		def post_params
			params.require(:post).permit(:content, :image, :font_color, :body_color)
		end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	def edit
		if Setting.count >= 1
			puts "ass"
			@setting = Setting.find(params[:id])
			p @setting
		else
			puts "titties"
			@setting = Setting.create
		end
	end

	def update
		@setting = Setting.find(params[:id])
		@setting.color = params[:setting][:color]
		if @setting.save
			flash[:success] = "site color updated!"
			redirect_to root_path
		else
			render :edit
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:home]
	def home
		@main_user = User.first
		@post = @main_user.posts.build
		if Setting.count >= 1
			@setting = Setting.first
		else
			@setting = Setting.create
		end
		session[:setting_id] = @setting.id
		session[:site_color] = @setting.color
		@feed_items = Post.order('created_at DESC')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<span>site built and designed by <em>Jaron Armiger</em></span>
	<span><em>jaron.armiger@gmail.com</em></span>
	<small>icons by <a href="https://www.glyphicons.com/"><em>glyphicons</em></a></small>
</footer>

app/views/layouts/_head.html.erb
<head>
	<title>Steven</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg " style="background-color: <%= session[:site_color] %>">
  <div class="top-wrapper">
  	<% if user_signed_in? %>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="glyphicon glyphicon-yen"></span>
	  </button>
	<% else %>
	  <%= link_to 'Sign in', new_user_session_path, class: 'login-button', class: 'nav-link btn sign-in-btn' %>
	<% end %>
	  <%= link_to root_path, class: "navbar-brand" do %>
	    <img src="<%= asset_path('ssil.png') %>" class="logo-img" alt="">
	  <% end %>

  </div>
  <% if user_signed_in? %>
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item mobile-nav-item">
	        <%= link_to 'Dashboard', root_path, class: 'nav-link' %>
	      </li>
	      <li class="nav-item desktop-nav-item">
	        <%= link_to root_path, class: 'nav-link' do %>
			  <span class="glyphicon glyphicon-home"></span>
	        <% end %>
	      </li>
	      <li class="nav-item">
	        <%= link_to 'Manage posts', '#', class: 'nav-link' %>
	      </li>
	      <li class="nav-item">
	        <%= link_to 'Change Color', edit_setting_path(session[:setting_id]), class: 'nav-link' %>
	      </li>
	      <li class="nav-item mobile-nav-item">
	      	<%= link_to 'Edit Account Details', edit_user_registration_path, class: 'nav-link' %>
	      </li>
	      <li class="nav-item mobile-nav-item">
			<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
	      </li>
	      <li class="dropdown desktop-nav-item">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">Account</b></a>
            <ul class="dropdown-menu dropdown-menu-right" style="background-color: <%= session[:site_color] %>">
                <li class="nav-item">
		      	<%= link_to 'Edit Account Details', edit_user_registration_path, class: 'nav-link' %>
		      </li>
		      <li class="nav-item">
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
		      </li>
            </ul>
          </li>
	    </ul>
	  </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body style="background-color: <%= session[:site_color] %>">
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="dummy"></div>
      <% if !flash.empty? %>
        <% flash.each do |msg_type, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{msg_type}" %>
        <% end %>
      <% end %>
      
      
      <%= yield %>
      <div class="push"></div>
    </div>
    <%= render 'layouts/footer' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'navbar', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post_wrapper">
	<div class="card" style="background-color: <%= post.body_color %>; color: <%= post.font_color %>">
		<%= image_tag post.image, class: "card-img-top" if post.image.attached? %>
	
		<div class="card-body">
			<p><%= post.content %></p>
			<span class="timestamp">
			posted <%= time_ago_in_words(post.created_at) %> ago.
			</span>
		</div>
		  <div class="card-body change-buttons-wrapper">
			<%= link_to post_path(post) do %>
				<span class="glyphicon glyphicon-eye-open"></span>
			<% end %>
			<% if user_signed_in? %>
				<%= link_to edit_post_path(post) do %>
					<span class="glyphicon glyphicon-pencil"></span>
				<% end %>
				<%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
				  <span class="glyphicon glyphicon-trash"></span>
				<% end %>
			<% end %>
		  </div>
	</div>
</div>

app/views/posts/_post_form.html.erb
<%= form_with(model: @post, local: true, class: "post-form") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="form-group text-input-div">
	  <%= f.text_area :content, placeholder: "How you feelin?", class: "form-control text-input" %>
	  <span id="x-button"></span>
	</div>
	<div class="styling form-group">
		<div class="color-pickers">
		  <div class="picker font-picker">
			<%= f.label :font_color %>
			<%= f.color_field :font_color %>
		  </div>
		  <div class="picker body-picker">
			<%= f.label :body_color %>
			<%= f.color_field :body_color %>
		  </div>
	    </div>
	    <div class="upload-div">
	      <span class="upload-photo"><%= yield(:change) %> Photo</span>
		  <label for="post_image" class="file-label"><span class="glyphicon glyphicon-camera"></span></label>
			<%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", class: "img-upload", id: "post_image" %>
		</div>
	</div>
	<div class="post-form-buttons">
		<%= f.submit yield(:submit), class: "share-button" %>
	</div>
	<%= javascript_include_tag 'post_form' %>
<% end %>

app/views/posts/edit.html.erb
<% provide :submit, "save changes" %>
<% provide :change, "Change" %>
<%= render 'posts/post_form' %>

app/views/posts/show.html.erb
<%= render @post %>

app/views/settings/edit.html.erb
<%= form_with(model: @setting, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
	<div class="user-color">
	  <%= f.label(:color) %>
	  <%= f.color_field :color %>
	  <div class="post-form-buttons">
		<%= f.submit "Save Changes", class: "color-button" %>
	  </div>
	</div>
	
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:submit, "share") %>
<% provide(:change, "Upload") %>
<% if user_signed_in? %>
  <%= render 'posts/post_form' %>
<% end %>
<%= render @feed_items %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>